### ISSUE TITLE
graphdatascience.error.unable_to_connect.UnableToConnectError

### ISSUE THREAD

**Issue by simoncharmms** [tomasonjo/NeoGPT-Explorer#5]
When running `import.py` I encounter:

```
raise UnableToConnectError(e)
graphdatascience.error.unable_to_connect.UnableToConnectError: {code: Neo.ClientError.Security.Unauthorized} {message: The client is unauthorized due to authentication failure.}
```

I tried changing 

```
user = "neo4j"
password = "pleaseletmein"
```

to my Neo4j credentials, which did not help. Should I adjust anything else in the params here?

Thanks for your response!

**Comment by tomasonjo** [comment]
There is something wrong with authorization. If you have different credentials you need to set them accordingly.

**Comment by simoncharmms** [comment]
Thanks, as I said, I already tried that. Do I also have to change `host = "bolt://localhost:7687"` or any other parameter?

**Comment by tomasonjo** [comment]
You have to change all the relevant credentials to be valid for the database that you use

**Comment by simoncharmms** [comment]
Thanks. I work with `gds` for the first time - found out that I need to create an instance in [neo4j aura](https://console.neo4j.io/) and replace `"bolt://localhost:7687"`by the link to the instance `"neo4j+s://[...]:7687"`. In Neo4j, you can retrieve your credentials by `$:server status`.
